# Generated by Django 2.2.4 on 2020-04-04 16:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neparu', '0003_auto_20200404_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='receiver',
        ),
        migrations.AddField(
            model_name='inbox',
            name='receiver',
            field=models.ManyToManyField(blank=True, null=True, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
