# Generated by Django 2.2.4 on 2020-04-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neparu', '0006_auto_20200405_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('', ''), ('AB+', 'AB+'), ('AB-', 'AB-'), ('A+', 'A+'), ('B+', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-')], default='', max_length=10),
        ),
    ]
